meeteo_meeteo_homepage:
    path:     /
    defaults: { _controller: MeeteoMeeteoBundle:Default:index }

_report:
    path:     /report/{lat}/{lon}
    defaults: { _controller: MeeteoMeeteoBundle:Report:Report }

_manage:
    path:     /Manage
    defaults: { _controller: MeeteoMeeteoBundle:Manage:Manage }

_vent:
    path:     /vent
    defaults: { _controller: MeeteoMeeteoBundle:Default:Vents }


_temperature:
    path:     /temperature
    defaults: { _controller: MeeteoMeeteoBundle:Default:Temperature }
