meeteo_meeteo_homepage:
    path:     /
    defaults: { _controller: MeeteoMeeteoBundle:Default:index }

_report:
    path:     /report/{lat}/{lon}
    defaults: { _controller: MeeteoMeeteoBundle:Report:Report }
