meeteo_meeteo:
    resource: "@MeeteoMeeteoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

google_login:
    pattern: /login/check-google

#login:
#    pattern:   /login
#    defaults:  { _controller: FoggylineTickerBundle:Security:login }

#login_check:
#    pattern:   /login_check
#

logout:
    path:   /logout

foggyline_ticker:
    resource: "@FoggylineTickerBundle/Resources/config/routing.yml"
    prefix:   /
